### ISSUE TITLE
API doesn't work.

### ISSUE THREAD

**Issue by FunnyBuddys** [TwistedAsylumMC/Scoreboards#2]
![screenshot_16](https://user-images.githubusercontent.com/16995710/47265880-05115000-d52f-11e8-8583-a723b8361d2e.png)

**Comment by TwistedAsylumMC** [comment]
in  what function are you  using the api?

**Comment by FunnyBuddys** [comment]
JoinEvent

**Comment by TwistedAsylumMC** [comment]
can i see your code to see if i can replicate this issue?

**Comment by drewsucksatlife** [comment]
oof

**Comment by FunnyBuddys** [comment]
I used your API.
1 by 1

**Comment by TwistedAsylumMC** [comment]
i said send it

**Comment by Wolfkid200444** [comment]
rip
